import django_heroku_template.settings as settings
import stripe

STRIPE_TEST_SECRET_KEY = 'sk_test_5KgaXkwO9swdZInrWVDsZX33'
STRIPE_TEST_PUBLISHABLE_KEY = 'pk_test_oFUfikhMAgGNmXaKWU7MjRYl'

STRIPE_LIVE_SECRET_KEY = 'sk_live_QEo2abR75wWNyiZxXjEHsifA'
STRIPE_LIVE_PUBLISHABLE_KEY = 'pk_live_SKx600v90YGGvlcJADJHn1ki'

if settings.DEBUG:
    STRIPE_SECRET_KEY = STRIPE_TEST_SECRET_KEY
    STRIPE_PUBLISHABLE_KEY = STRIPE_TEST_PUBLISHABLE_KEY

else:
    STRIPE_SECRET_KEY = STRIPE_LIVE_SECRET_KEY
    STRIPE_PUBLISHABLE_KEY = STRIPE_LIVE_PUBLISHABLE_KEY

stripe.api_key = STRIPE_SECRET_KEY

